export const langsOwnLang = {
    "af":"Nederlands",
    "af-ZA":"Nederlands - Suid-Afrika",
    "sq":"Shqipëria",
    "sq-AL":"Shqipëria-Shqipëria",
    "ar":"عربي",
    "ar-DZ":"عربي - الجزائر",
    "ar-BH":"العربية - البحرين",
    "ar-EG":"عربي - مصر",
    "ar-IQ":"عربي - العراق",
    "ar-JO":"عربي - الاردن",
    "ar-KW":"عربي - الكويت",
    "ar-LB":"عربي - لبنان",
    "ar-LY":"عربي - ليبيا",
    "ar-MA":"عربي - المغرب",
    "ar-OM":"عربي - عمان",
    "ar-QA":"عربي - قطر",
    "ar-SA":"عربي - السعودية",
    "ar-SY":"عربي - الجمهورية السورية",
    "ar-TN":"عربي - جمهورية شمال إفريقيا",
    "ar-AE":"العربية - الإمارات العربية المتحدة",
    "ar-YE":"عربي - اليمن",
    "hy":"Հայաստան",
    "hy-AM":"Հայաստան - Հայաստան",
    "az":"Azərbaycan",
    "az-AZ-Cyrl":"Azərbaycan (Kiril)",
    "az-AZ-Latn":"Azərbaycan (Latın)",
    "eu":"euskara",
    "eu-ES":"euskara - euskara",
    "be":"Corsu",
    "be-BY":"Corsu-Bielorussia",
    "bg":"български",
    "bg-BG":"Българин - България",
    "ca":"català",
    "ca-ES":"Català - Catalunya",
    "zh-HK":"中文-中國香港",
    "zh-MO":"中文-中国澳门",
    "zh-CN":"中文-中国",
    "zh-CHS":"中文",
    "zh-SG":"中文-新加坡",
    "zh-TW":"中文-中國台灣",
    "zh-CHT":"中文",
    "hr":"Hrvatski",
    "hr-HR":"Hrvatski – Hrvatska",
    "cs":"čeština",
    "cs-CZ":"čeština",
    "da":"dansk",
    "da-DK":"Dansk - Danmark",
    "div":"हिंदी",
    "div-MV":"हिन्दी-मालदीव",
    "nl":"Nederlands",
    "nl-BE":"Nederlands - België",
    "nl-NL":"Nederlands - Nederland",
    "en":"English",
    "en-AU":"English - Australia",
    "en-BZ":"English - Belize",
    "en-CA":"English - Canada",
    "en-CB":"English - Caribbean",
    "en-IE":"English - Irish",
    "en-JM":"English - Jamaica",
    "en-NZ":"English - New Zealand",
    "en-PH":"English - Philippines",
    "en-ZA":"English - South Africa",
    "en-TT":"English - Trinidad and Tobago",
    "en-GB":"English - United Kingdom",
    "en-US":"English - United States",
    "en-ZW":"English - Zimbabwe",
    "et":"eesti keel",
    "et-EE":"eesti - eesti keel",
    "fo":"Kreyòl ayisyen",
    "fo-FO":"Kreyòl ayisyen - Zile Feroe",
    "fa":"فارسی",
    "fa-IR":"فارسی - پادشاهی ایران",
    "fi":"Suomalainen",
    "fi-FI":"suomi - Suomi",
    "fr":"Français",
    "fr-BE":"Français - Belgique",
    "fr-CA":"Français - Canada",
    "fr-FR":"France francaise",
    "fr-LU":"Français - Luxembourgeois",
    "fr-MC":"Français - Monaco",
    "fr-CH":"Français - Suisse",
    "gl":"galego",
    "gl-ES":"Galego - Galicia",
    "ka":"ქართული",
    "ka-GE":"ქართული - საქართველო",
    "de":"Deutsch",
    "de-AT":"Deutsch - Österreich",
    "de-DE":"Deutsches Deutschland",
    "de-LI":"Deutsch - Liechtenstein",
    "de-LU":"Deutsch - Luxemburg",
    "de-CH":"Deutsch - Schweiz",
    "el":"Ελληνικά",
    "el-GR":"Ελληνικά - Ελλάδα",
    "gu":"ગુજરાતી",
    "gu-IN":"ગુજરાતી-ભારત",
    "he":"עִברִית",
    "he-IL":"עברית - ישראל",
    "hi":"हिंदी",
    "hi-IN":"हिंदी भारत",
    "hu":"Magyar",
    "hu-HU":"magyar - Magyarország",
    "is":"íslenskur",
    "is-IS":"Íslenska - Ísland",
    "id":"bahasa Indonesia",
    "id-ID":"Indonesia - Indonesia",
    "it":"italiano",
    "it-IT":"Italiano - Italia",
    "it-CH":"Italiano - Svizzera",
    "ja":"日语",
    "ja-JP":"日本語 - 日本",
    "kn":"ಕನ್ನಡ",
    "kn-IN":"ಕನ್ನಡ-ಭಾರತ",
    "kk":"қазақ",
    "kk-KZ":"Қазақ - қазақ",
    "kok":" कोंकणी",
    "kok-IN":"Konkani - India",
    "ko":"한국인",
    "ko-KR":"한국어 - 한국",
    "ky":"Қазақстан",
    "ky-KZ":"Қазақ - қазақ",
    "lv":"latviski",
    "lv-LV":"Latviski - Latvija",
    "lt":"lietuvių",
    "lt-LT":"Lietuvis - Lietuva",
    "mk":"македонски",
    "mk-MK":"македонско-албански",
    "ms":"Melayu",
    "ms-BN":"Melayu - Brunei",
    "ms-MY":"Melayu - Malaysia",
    "mr":"मराठी",
    "mr-IN":"मराठी-भारत",
    "mn":"Монгол",
    "mn-MN":"Монгол",
    "no":"norsk",
    "nb-NO":"norsk",
    "nn-NO":"norsk",
    "pl":"Polski",
    "pl-PL":"Polski",
    "pt":"Português",
    "pt-BR":"Português - Brasil",
    "pt-PT":"Português - Portugal",
    "pa":"ਪੰਜਾਬੀ",
    "pa-IN":"ਪੰਜਾਬੀ-ਭਾਰਤ",
    "ro":"ਰੋਮਾਨੀਅਨ",
    "ro-RO":"ਰੋਮਾਨੀਅਨ",
    "ru":"Русский",
    "ru-RU":"Русский",
    "sa":"संस्कृत",
    "sa-IN":"संस्कृत-भारत",
    "sr-SP-Cyrl":"српски (ћирилица)",
    "sr-SP-Latn":"Serbian (Latin)",
    "sk":"slovenský",
    "sk-SK":"Slovák - Slovensko",
    "sl":"Slovenščina",
    "sl-SI":"Slovenščina",
    "es":"español",
    "es-AR":"Español - Argentina",
    "es-BO":"Español - Bolivia",
    "es-CL":"Español - Chile",
    "es-CO":"Español - Colombia",
    "es-CR":"Español - Costa Rica",
    "es-DO":"español - dominicano",
    "es-EC":"Español - Ecuador",
    "es-SV":"Español - El Salvador",
    "es-GT":"Español - Guatemala",
    "es-HN":"Español - Honduras",
    "es-MX":"Español - México",
    "es-NI":"Español - Nicaragua",
    "es-PA":"Español - Panamá",
    "es-PY":"Español - Paraguay",
    "es-PE":"Español - Perú",
    "es-PR":"Español - Puerto Rico",
    "es-ES":"Español - España",
    "es-UY":"español - uruguayo",
    "es-VE":"Español - Venezuela",
    "sw":"kiswahili",
    "sw-KE":"Swahili-Kenya",
    "sv":"svenska språket",
    "sv-FI":"svensk-finsk",
    "sv-SE":"Svenska - Sverige",
    "syr":"ܣܘܪܝܝܐ",
    "syr-SY":"ܣܘܪܝܝܐ",
    "ta":"தமிழ்",
    "ta-IN":"தமிழ்-இந்தியா",
    "tt":"Татар",
    "tt-RU":"Татар-рус",
    "te":"తెలుగు",
    "te-IN":"తెలుగు-భారతదేశం",
    "th":"ไทย-ไทย",
    "th-TH":"ไทย-ไทย",
    "tr":"Türkçe",
    "tr-TR":"Türkçe",
    "uk":"Україна",
    "uk-UA":"Україна",
    "ur":"اردو",
    "ur-PK":"اردو پاکستان",
    "uz":"o'zbek",
    "uz-UZ-Cyrl":"O'zbek (kirill)",
    "uz-UZ-Latn":"Uzbek (Latin)",
    "vi":"Tiếng Việt",
    "vi-VN":"Tiếng Việt"
}