/** 语言-地区 代码的英文名称 */
export const langsEnglish = {
    "af": "Common Dutch",
    "af-ZA":"Common Dutch-South Africa",
    "sq": "Albania",
    "sq-AL":"Albania-Albania",
    "ar": "Arabic",
    "ar-DZ":"Arabic-Algeria",
    "ar-BH":"Arabic-Bahrain",
    "ar-EG":"Arabic-Egyptian",
    "ar-IQ":"Arabic-Iraq",
    "ar-JO":"Arabic-Jordan",
    "ar-KW":"Arabic-Kuwait",
    "ar-LB":"Arabic-Lebanon",
    "ar-LY":"Arabic-Libya",
    "ar-MA":"Arabic-Morocco",
    "ar-OM":"Arabic-Oman",
    "ar-QA":"Arabic-Qatar",
    "ar-SA":"Arabic-Saudi Arabia",
    "ar-SY":"Arabic-Syrian Republic",
    "ar-TN":"Arabic - Republic of North Africa",
    "ar-AE":"Arabic-United Arab Emirates",
    "ar-YE": "Arabic-Yemen",
    "hy": "Armenia",
    "hy-AM":"Armenian-Armenian",
    "az": "Azerbaijan",
    "az-AZ-Cyrl":"Azerbaijan(Cyrillic)",
    "az-AZ-Latn":"Azerbaijan(Latin)",
    "eu": "Basque",
    "eu-ES":"Basque-Basque",
    "be": "Belarusian",
    "be-BY":"Belarusian-Belarusian",
    "bg": "Bulgaria",
    "bg-BG":"Bulgaria-Bulgaria",
    "ca": "Catalonia",
    "ca-ES":"Catalonia-Catalonia",
    "zh-HK":"Chinese-Hong Kong, China",
    "zh-MO":"Mandarin-Macao, China",
    "zh-CN":"Mandarin-China",
    "zh-CHS":"Mandarin-Single",
    "zh-SG":"Chinese-Singapore",
    "zh-TW":"Chinese-Taiwan",
    "zh-CHT":"Chinese-Traditional",
    "hr":"Croatia",
    "hr-HR":"Croatia-Croatia",
    "cs": "Czech Republic",
    "cs-CZ": "Czech Republic",
    "da": "Danish",
    "da-DK":"Danish-Denmark",
    "div": "Dhivehi",
    "div-MV":"Dhivehi-Maldives",
    "nl": "Netherlands",
    "nl-BE":"Netherlands-Belgium",
    "nl-NL":"Netherlands-Netherlands",
    "en": "United Kingdom",
    "en-AU":"United Kingdom-Australia",
    "en-BZ":"United Kingdom-Belize",
    "en-CA":"United Kingdom-Canada",
    "en-CB":"United Kingdom-Caribbean",
    "en-IE":"UK-Ireland",
    "en-JM":"United Kingdom-Jamaica",
    "en-NZ":"United Kingdom - New Zealand",
    "en-PH":"British-Philippine Republic",
    "en-ZA":"UK-South Africa",
    "en-TT":"United Kingdom - Republic of Trinidad and Tobago",
    "en-GB": "United Kingdom - United Kingdom",
    "en-US": "United Kingdom-United States",
    "en-ZW":"UK-Zimbabwe",
    "et": "Estonia",
    "et-EE":"Estonia-Estonia",
    "fo": "Faroese",
    "fo-FO":"Faroese",
    "fa": "Persian",
    "fa-IR":"Persian-Kingdom of Iran",
    "fi": "Finnish",
    "fi-FI":"Finnish-Finland",
    "fr": "France",
    "fr-BE":"France-Belgium",
    "fr-CA":"France-Canada",
    "fr-FR": "France-France",
    "fr-LU":"France-Luxembourg",
    "fr-MC":"France-Monaco",
    "fr-CH":"France-Switzerland",
    "gl":"Galicia",
    "gl-ES":"Galicia-Galicia",
    "ka":"Georgia",
    "ka-GE":"Georgia-Georgia",
    "de": "Germany",
    "de-AT":"Germany-Austria",
    "de-DE": "Germany - Germany",
    "de-LI":"Germany - Liechtenstein",
    "de-LU":"Germany-Luxembourg",
    "de-CH":"Germany-Switzerland",
    "el": "Greece",
    "el-GR":"Greece-Greece",
    "gu": "Gujarati",
    "gu-IN":"Gujarati-India",
    "he": "Hebrew",
    "he-IL": "Hebrew-Israel",
    "hi": "Hindi",
    "hi-IN":"North Indian-India",
    "hu": "Hungary",
    "hu-HU":"Hungary-Hungary",
    "is": "Icelandic",
    "is-IS":"Icelandic-Icelandic",
    "id": "Indonesia",
    "id-ID": "Indonesia-Indonesia",
    "it": "Italy",
    "it-IT": "Italy - Italy",
    "it-CH":"Italy-Switzerland",
    "ja": "Japan",
    "ja-JP": "Japan-Japan",
    "kn": "Kannada",
    "kn-IN":"Kannada-India",
    "kk": "Kazakh",
    "kk-KZ":"Kazakh-Kazakh",
    "kok": "Konkani",
    "kok-IN":"Konkani-India",
    "ko": "Korea",
    "ko-KR":"Korea-Korea",
    "ky": "Kyrgyz",
    "ky-KZ":"Kyrgyz-Kazakh",
    "lv": "Latvia",
    "lv-LV":"Latvian-Latvian",
    "lt":"Lithuania",
    "lt-LT":"Lithuania-Lithuania",
    "mk": "Macedonia",
    "mk-MK":"Macedonia-FYROM",
    "ms": "Malay",
    "ms-BN":"Malay-Brunei",
    "ms-MY":"Malay-Malaysia",
    "mr": "Marathi",
    "mr-IN":"Marathi-India",
    "mn": "Mongolia",
    "mn-MN": "Mongolia-Mongolia",
    "no": "Norway",
    "nb-NO":"Norway-Bokm?l",
    "nn-NO":"Norway-Nynorsk",
    "pl": "Poland",
    "pl-PL":"Poland-Poland",
    "pt": "Portugal",
    "pt-BR":"Portugal-Brazil",
    "pt-PT": "Portugal-Portugal",
    "pa": "Punjab language",
    "pa-IN":"Punjab-India",
    "ro":"Romanian",
    "ro-RO":"Romanian-Romania",
    "ru": "Russia",
    "ru-RU": "Russia-Russia",
    "sa": "Sanskrit",
    "sa-IN":"Sanskrit-India",
    "sr-SP-Cyrl":"Serbia-(Cyrillic)",
    "sr-SP-Latn": "Serbia (Latin)",
    "sk": "Slovakia",
    "sk-SK":"Slovakia-Slovakia",
    "sl":"Slovenia",
    "sl-SI":"Slovenia-Slovenia",
    "es": "Spain",
    "es-AR":"Spain-Argentina",
    "es-BO":"Spain-Bolivia",
    "es-CL":"Spain-Chile",
    "es-CO":"Spain-Colombia",
    "es-CR":"Spain-Costa Rica",
    "es-DO":"Spain-Dominican Republic",
    "es-EC":"Spain-Ecuador",
    "es-SV":"Spain-El Salvador",
    "es-GT":"Spain-Guatemala",
    "es-HN":"Spain-Honduras",
    "es-MX":"Spain-Mexico",
    "es-NI":"Spain-Nicaragua",
    "es-PA":"Spain-Panama",
    "es-PY":"Spain-Paraguay",
    "es-PE":"Spain-Peru",
    "es-PR":"Spain-Puerto Rico",
    "es-ES":"Spain-Spain",
    "es-UY":"Spain-Uruguay",
    "es-VE":"Spain-Venezuela",
    "sw": "Swahili",
    "sw-KE":"Swahili-Kenya",
    "sv": "Sweden",
    "sv-FI":"Sweden-Finland",
    "sv-SE":"Sweden-Sweden",
    "syr": "Syriac",
    "syr-SY":"Syriac-Syrian Republic",
    "ta": "Tamil",
    "ta-IN":"Tamil-India",
    "tt": "Tatar",
    "tt-RU":"Tatar-Russia",
    "te": "Telugu",
    "te-IN":"Telugu-India",
    "th": "Thailand",
    "th-TH": "Thailand-Thailand",
    "tr": "Turkish",
    "tr-TR":"Turkish-Turkey",
    "uk": "Ukraine",
    "uk-UA":"Ukraine-Ukraine",
    "ur": "Urdu",
    "ur-PK":"Urdu-Pakistan",
    "uz": "Uzbek",
    "uz-UZ-Cyrl":"Uzbek-(Cyrillic)",
    "uz-UZ-Latn": "Uzbek (Latin)",
    "vi": "Vietnam",
    "vi-VN":"Vietnam-Vietnam"
}